version: '3.8'

services:
  # PHP-FPM Service
  php:
    container_name: jobsglobal_php
    build:
      context: .
      dockerfile: docker/Dockerfile
    volumes:
      - ./:/var/www
    networks:
      - app-network
    environment:
      - PHP_FPM_PM_MAX_CHILDREN=10
    expose:
      - "9000"  # Exposing port for FPM
      - "6001"

  # Nginx Service
  nginx:
    image: nginx:alpine
    container_name: jobsglobal_nginx
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./docker/nginx/snippets/fastcgi-php.conf:/etc/nginx/snippets/fastcgi-php.conf
    ports:
      - "8080:80"  # Exposing port for web access
    depends_on:
      - php
    networks:
      - app-network

  mailhog:
    image: mailhog/mailhog
    container_name: jobsglobal_mailhog
    ports:
      - "1025:1025"
      - "8025:8025"
    networks:
      - app-network


  mysql:
    image: mariadb
    container_name: jobsglobal_db
    environment:
      MYSQL_DATABASE: jobsglobal_db
      MYSQL_USERNAME: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./dbdata:/var/lib/mysql/
    ports:
      - "3308:3308"
    networks:
      - app-network


  phpmyadmin:
    container_name: jobsglobal_pma
    image: phpmyadmin
    restart: always
    ports:
      - 8087:80
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=jobsglobal_db
      - PMA_USER=root
      - PMA_PASSWORD=root
      - MAX_EXECUTION_TIME=3600
      - UPLOAD_LIMIT=512M
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
